
package snsoft.tss.quote.chance.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FtcCenterWebServiceBasService", targetNamespace = "http://cxf.chance.quote.tss.snsoft/", wsdlLocation = "http://101.96.134.180:8090/mnt/uiinvoke/CLOUD_STANDARD/ws-snsoft.cargo.center.ws.FtcCenterWebServiceBas?WSDL")
public class FtcCenterWebServiceBasService
    extends Service
{

    private final static URL FTCCENTERWEBSERVICEBASSERVICE_WSDL_LOCATION;
    private final static WebServiceException FTCCENTERWEBSERVICEBASSERVICE_EXCEPTION;
    private final static QName FTCCENTERWEBSERVICEBASSERVICE_QNAME = new QName("http://cxf.chance.quote.tss.snsoft/", "FtcCenterWebServiceBasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://101.96.134.180:8090/mnt/uiinvoke/CLOUD_STANDARD/ws-snsoft.cargo.center.ws.FtcCenterWebServiceBas?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FTCCENTERWEBSERVICEBASSERVICE_WSDL_LOCATION = url;
        FTCCENTERWEBSERVICEBASSERVICE_EXCEPTION = e;
    }

    public FtcCenterWebServiceBasService() {
        super(__getWsdlLocation(), FTCCENTERWEBSERVICEBASSERVICE_QNAME);
    }

    public FtcCenterWebServiceBasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FTCCENTERWEBSERVICEBASSERVICE_QNAME, features);
    }

    public FtcCenterWebServiceBasService(URL wsdlLocation) {
        super(wsdlLocation, FTCCENTERWEBSERVICEBASSERVICE_QNAME);
    }

    public FtcCenterWebServiceBasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FTCCENTERWEBSERVICEBASSERVICE_QNAME, features);
    }

    public FtcCenterWebServiceBasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FtcCenterWebServiceBasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FtcCenterWebServiceBas
     */
    @WebEndpoint(name = "FtcCenterWebServiceBasPort")
    public FtcCenterWebServiceBas getFtcCenterWebServiceBasPort() {
        return super.getPort(new QName("http://cxf.chance.quote.tss.snsoft/", "FtcCenterWebServiceBasPort"), FtcCenterWebServiceBas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FtcCenterWebServiceBas
     */
    @WebEndpoint(name = "FtcCenterWebServiceBasPort")
    public FtcCenterWebServiceBas getFtcCenterWebServiceBasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxf.chance.quote.tss.snsoft/", "FtcCenterWebServiceBasPort"), FtcCenterWebServiceBas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FTCCENTERWEBSERVICEBASSERVICE_EXCEPTION!= null) {
            throw FTCCENTERWEBSERVICEBASSERVICE_EXCEPTION;
        }
        return FTCCENTERWEBSERVICEBASSERVICE_WSDL_LOCATION;
    }

}
